name:                wordlizer
version:             0.1.0.0
license:             BSD3
author:              Alexis Kalderimis
copyright:           2022 Alexis Kalderimis
# gitlab:              alexkalderimis/wordlizer

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitLab at <https://gitlab.com/alexkalderimis/wordlizer>

dependencies:
- base >= 4.11 && < 10
- rio >= 0.1.12.0
- text
- parallel
- random
- foldl
- rainbow
- hashable
- aeson
- time
- bytestring
- directory
- filepath
- binary
- SHA

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  wordlizer:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - wordlizer
    - optparse-simple
    - xdg-basedir

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  wordlizer-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - wordlizer
    - hspec
    - QuickCheck

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
